### ISSUE TITLE
x25519 documentation outdated?

### ISSUE THREAD

**Issue by XiovV** [dint-dev/cryptography#11]
Hello, it seems like you've got 2 issues in the docs for x25519. 
1.) in the line 
`final remoteKeyPair = await x5519.newKeyPair();` 
you put `x5519` instead of `x25519`. 
2.) in the line 
`print('Shared secret: ${secretKey.bytes}');` 
there's no such thing as `bytes`. 

Am I doing something wrong or are the docs work in progress?

**Comment by XiovV** [comment]
After looking at the code it seems like .bytes should be replaced with .extractSync()?

**Comment by terrier989** [comment]
Thanks for reporting the error in the documentation! :)

I'll fix this.
