### ISSUE TITLE
CryptographyFlutterPlugin.swift:21:101: error: cannot call value of non-function type (macOS)

### ISSUE THREAD

**Issue by VadimBliz** [dint-dev/cryptography#112]
The log is:

.2/macos/Classes/CryptographyFlutterPlugin.swift:21:101: error: cannot call value of non-function type 'FlutterBinaryMessenger'
        let channel = FlutterMethodChannel(name: "cryptography_flutter", binaryMessenger: registrar.messenger())
                                                                                          ^        ~~

Command CompileSwiftSources failed with a nonzero exit code
Command CompileSwiftSources failed with a nonzero exit code
** BUILD FAILED **

Exception: Build process failed

flutter doctor -v

[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale ru-UA)
    • Flutter version 3.0.5 at /opt/homebrew/Caskroom/flutter/2.5.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (12 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/elereman/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/elereman/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/liberica-jdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_312-b07)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[!] Android Studio
    • Android Studio at /Users/elereman/Library/Application\ Support/Google/AndroidStudio2020.3/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Users/elereman/Library/Application\ Support/Google/AndroidStudio2020.3/Contents
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.6008.17

[✓] Connected device (4 available)
    • iPhone SE (3rd generation) (mobile)  • 3581BEDE-02AA-416C-B324-0EFE9A7BDE37 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • iPod touch (7th generation) (mobile) • 4C887631-1B4F-4A0F-AABB-B0CE8257CCC1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)                      • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

MacBook with Apple M1 chip

**Comment by terrier989** [comment]
This should have been fixed in cryptography_flutter 2.1.0.
