### ISSUE TITLE
Is "noise_protocol" abandoned?

### ISSUE THREAD

**Issue by bcattaneo** [dint-dev/cryptography#118]
Hi,

Asking here as an issue because this seem to be the project's homepage, I'm referring to https://pub.dev/packages/noise_protocol

Is this project alive? where can I found its code on github (or any other place)

I've found a couple of issues with it so far:
- it has several outdated dependencies and it's pretty much impossible to include it on any project that requires an updated "cryptography" module (>1.0.0).
- "example.dart" doesn't run at all
- pretty much all tests seem to be failing

Thanks in advance!

EDIT: related to https://github.com/dint-dev/cryptography/issues/83

**Comment by terrier989** [comment]
There is no active work on it.
