### ISSUE TITLE
Argon2id dart implementation throws UnimplementedError

### ISSUE THREAD

**Issue by anidotnet** [dint-dev/cryptography#121]
When can we expect the full implementation of Argon2id in the lib? Currently it throws UnimplmentedError from [here](https://github.com/dint-dev/cryptography/blob/854472b69a604c5ee262019ce8d2ad5bf4ee6ce5/cryptography/lib/src/dart/argon2.dart#L73).

**Comment by terrier989** [comment]
I'd love to finish it someday, but if anyone accomplishes it before me please make a pull request. 👍

**Comment by terrier989** [comment]
Thank you for the issue report! Argon2id has been implemented now and it passes tests in all platforms.
