### ISSUE TITLE
Plans to support RSA?

### ISSUE THREAD

**Issue by wujek-srujek** [dint-dev/cryptography#13]
First of all, thank for this library. I have been struggling with PointyCastle and anything based on it, as it seems to have an issue with AES encryption/decryption of bigger files, performance was appalling. This library has been really fast in my tests, and I verified the data against samples fro other library (a C++ based oldie) and it is correct. Kudos to you.

I currently need to support both AES and RSA, and it means I would need to integrate this library and another one for RSA. Are you guys planning on adding RSA support at some point?

**Comment by terrier989** [comment]
Thanks for sharing a positive experience! :)

There are no plans to support RSA.

**Comment by wujek-srujek** [comment]
That's a pity. May I ask why? Is it particularly hard to implement, or doesn't fit in thematically with this library?

**Comment by terrier989** [comment]
This package was written because we had specific needs and RSA isn't one of them. If some organization contributes RSA support, it could be considered.

**Comment by terrier989** [comment]
I added support for RSA signatures in browsers using Web Cryptography API, which was very fast to write. The package still welcomes pure Dart implementations (under Apache License 2.0) if someone wants to contribute.
