### ISSUE TITLE
[Web] Key data must be a BufferSource for non-JWK formats

### ISSUE THREAD

**Issue by Amphaal** [dint-dev/cryptography#131]
Bug introduced in 2.1.0 - HMAC256 for `DartChacha20` at least, `decrypt` now fails. 

<img width="467" alt="Capture d’écran 2023-02-22 à 23 49 20" src="https://user-images.githubusercontent.com/13903151/220778027-1cb76171-6db3-481d-b375-356ed662c3b3.png">

Fails here:

<img width="1051" alt="Capture d’écran 2023-02-22 à 23 51 48" src="https://user-images.githubusercontent.com/13903151/220778499-12277f78-6179-4e88-954f-dd6712547d8c.png">

<img width="1171" alt="Capture d’écran 2023-02-22 à 23 52 31" src="https://user-images.githubusercontent.com/13903151/220778817-6e659a6c-cb71-486b-8039-a69ebf07ce55.png">

**Comment by terrier989** [comment]
This was fixed in 2.2.0.
