### ISSUE TITLE
How to export/import private keys

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [dint-dev/cryptography#148]
Hi,
Disclaimer: I'm relatively new to dart/flutter and I may have missed the obvious way.
I use the following to export the private key and store it to a file for re-load after re-opening the app
```
  final algorithm = Ed25519();
  final keyPair = await algorithm.newKeyPair();
  final privateKey = await keyPair.extractPrivateKeyBytes();
  final privateKeyBase64 = await base64.encode(privateKey);
// ... write base64 encoded string to file
```
How can I instantiate an `Ed25519` key pair from the private key which I dumped to the file?
Thanks in advance!

**Comment by HerrMuellerluedenscheid** [comment]
Ah, I have to instantiate a `SimpleKeyPairData`:

```
final keyPairLoaded = SimpleKeyPairData(privateKeyBase64Decoded, publicKey: publicKey, type: KeyPairType.ed25519);
```

**Comment by muhdlaziem** [comment]
@HerrMuellerluedenscheid what about constructing public key from encoded string?

**Comment by muhdlaziem** [comment]
> @HerrMuellerluedenscheid what about constructing public key from encoded string?

`SimplePublicKey(
        base64Decode("kvtIPK3Ze8Dzsv9y1R1vAgASaiOPEPTQ0fojai2RTyE=")` will do. thanks !
