### ISSUE TITLE
Argon2id kda throws UnimplementedError - Any timeframe?

### ISSUE THREAD

**Issue by mgb-mat** [dint-dev/cryptography#161]
After trying to figure out if my inputs/parameters weren't supported yet for the `Argon2id` key derivation, I found out that the function simply [throws at the end](https://github.com/dint-dev/cryptography/blob/b05e0ed1defbb7fb32c274f19344c6eb08344584/cryptography/lib/src/dart/argon2.dart#L124):

```dart
throw UnimplementedError('Does not pass tests yet.');
```

Is there any information or discussion regarding these tests' development? I was led to using that algorithm by reading the [documentation](https://pub.dev/documentation/cryptography/latest/cryptography/Pbkdf2-class.html), which very clearly encourages Argon2id over Pbdkf2:

> PBKDF2 is a popular choice for password hashing, but much better algorithms exists (such as [Argon2id](https://pub.dev/documentation/cryptography/latest/cryptography/Argon2id-class.html)).

Maybe that should be made clearer in the documentation when an algorithm isn't yet supported, as to avoid wasting time trying to use it.

**Comment by terrier989** [comment]
Hi! Thank you for the feature request. Argon2id was implemented at v2.7.0.
