### ISSUE TITLE
Build error when using cryptography 2.6.0 and cryptography_flutter 2.3.1

### ISSUE THREAD

**Issue by svenopdehipt** [dint-dev/cryptography#162]
It is not possible to build a project with the new versions because of an build error.
The error is: `The type 'FlutterCryptography' must be 'base', 'final' or 'sealed' because the supertype 'BrowserCryptography' is 'base'.`

**Comment by terrier989** [comment]
Hi! Thank you for the issues report. This was fixed in 2.6.1.
