### ISSUE TITLE
UnimplementedError

### ISSUE THREAD

**Issue by Denmal1982** [dint-dev/cryptography#18]
I get this error when running the example

 final localKeyPair = await x25519.newKeyPair();
 final remoteKeyPair = await x5519.newKeyPair();

  var sharedSecret = await x25519.sharedSecret(
     localPrivateKey: localKeyPair.privateKey,
     remotePublicKey: remoteKeyPair.publicKey,
  );

`Unhandled exception:`
`UnimplementedError`
`#0      _EcdhNist.newKeyPairSync (package:cryptography/src/cryptography/algorithms/ec_dh_impl.dart:168:5)`
`#1      KeyExchangeAlgorithm.newKeyPair1(package:cryptography/src/cryptography/key_exchange_algorithm.dart:59:57)`

**Comment by terrier989** [comment]
Hi!
X25519 works in all platforms. Based on the stack trace, it looks like you are using P256, P384 or P512? Both the README and Dart reference say that these algorithms only work in browsers.
