### ISSUE TITLE
Any reason to not use crypto.subtle to generate symmetric keys in web context?

### ISSUE THREAD

**Issue by edyu** [dint-dev/cryptography#19]
First of all. Big thank you for creating this library. I went from a 3 minute keygen that uses pointycastle to under a minute so that's a huge improvement. I was in the middle of implementing my own wrapper when I saw this library so thank you!
Is there any reason to not use the subtle.generateKey for AES? If there is no reason I can do a pull request but just wondering whether I'm missing something.

Thank you

**Comment by edyu** [comment]
I added pull request #20 for this.

**Comment by terrier989** [comment]
Hi! Thanks for the feedback and the pull request! :) For simplicity all cipher secrets have been generated with `SecretKey.randomBytes(length)`. It uses `Random.secure()` in _dart:math_, which uses `window.crypto.getRandomValues()` in browsers. I agree that it would be better to generate keys with Web Cryptography API directly. I'll review the changes.

**Comment by edyu** [comment]
@terrier989 thanks

**Comment by terrier989** [comment]
This is fixed in 1.4.1.
