### ISSUE TITLE
X25519 - newline in public key

### ISSUE THREAD

**Issue by Designlico** [dint-dev/cryptography#22]
I'm trying to use X25519 generated keys in a system that encrypts data, this data will afterwards be decrypted on a web application.
I have an issue with a newline in the public key that is generated, if I remove it the decryption flow works as intended.
Sample generated key 87eed04189ee79daab010a1132002edd\n0280c2eab187d981dd693f269b69fe4d
Is this intended, accidental or am I missing something?

**Comment by terrier989** [comment]
How do you generate the hex string? `PublicKey` has `bytes`, which returns the raw bytes (32 bytes in this case).

**Comment by andreineacsu** [comment]
@terrier989 I'm jumping in here for my colleague. Here is the code for converting the `bytes` to `hex`:

`String get publicKey => hexFromBytes(_publicKey.bytes).replaceAll(' ', '');`

**Comment by apoleo88** [comment]
PublicKey has no longer bytes, how to retrieve it?
