### ISSUE TITLE
Takes too long to decrypt video on Android device

### ISSUE THREAD

**Issue by jazeelqb** [dint-dev/cryptography#23]
It takes around 4 min to decrypt a video file of ~70MB on an android device. Not sure if I'm doing it wrong, any help is much appreciated.
This is my code:
```dart
const cipher = chacha20Poly1305Aead;
final secretKey = SecretKey(base64Decode(decryptKey));
final iv = Nonce(base64Decode(decryptIV));
final decrypted = await cipher.decrypt(encryptedContent, secretKey: secretKey, nonce: iv);
await decryptedFile.writeAsBytes(decrypted);
```

**Comment by terrier989** [comment]
The current Poly1305 implementation uses BigInt for multiplying scalars in the 2^130-5 field, which is very inefficient. We want to fix this at some point.

If you can choose any cipher, `aesGcm` or `CipherWithAppendedMac(chacha20, Hmac(sha256))` will perform much better.

**Comment by terrier989** [comment]
This is definitely fixed in the latest version.
