### ISSUE TITLE
Option to seperate message authentication code (MAC) from encrypted message

### ISSUE THREAD

**Issue by ONLYstcm** [dint-dev/cryptography#24]
I'm running AES-GCM across two different platform and libraries. Specifically Arduino/Mbedtls and Dart/cryptography, however implementation of the authentication is different. Mbedtls write the authentication tag to a separate output input for the tag is also separate from the encryption. I think there should be an option for separating the tag in this library as well so that it can be used across multiple platforms.

**Comment by ONLYstcm** [comment]
Not a major issue, since the AES tag is appended to the cipher, one can just use sublist to separate the tag from the cipher. Just an option

**Comment by terrier989** [comment]
I agree that this should be fixed.

**Comment by terrier989** [comment]
This is fixed in 2.0.0-nullsafety.0.
