### ISSUE TITLE
Is it possible to use with SecureSocket?

### ISSUE THREAD

**Issue by idc-snoe** [dint-dev/cryptography#26]
Hi, I don't know crypto very well but I have a client using dart.io.SecureSocket failing to connect to a server using a ED22519 cert. Can this library help with that? Is it possible to plug this library into that API or is there another approach or example of using this to do TLS (I'm wary of coding the TLS handshake myself with RawSocket)?

**Comment by terrier989** [comment]
Hi! Thanks for the interest in this package! TLS sockets in dart:io have `onBadCertificate` parameter, which can be used to implement custom validation logic. This package doesn't do X509 DER/PEM parsing.
