### ISSUE TITLE
Crypto key cache on web breaks with dart2js

### ISSUE THREAD

**Issue by CDDelta** [dint-dev/cryptography#37]
The crypto key cache [here](https://github.com/dint-dev/cryptography/blob/04b0746cc39dd92dfa5ba71d117120e5f853297b/cryptography/lib/src/web_crypto/impl/aes.dart#L87) breaks silently when compiled with dart2js.

Not sure on what to do here... I've temporarily removed the cache for myself.

To reproduce try encrypting some data using AES twice using the same key in a script compiled with dart2js.

**Comment by terrier989** [comment]
Thanks for the issue report! The CryptoKey caching was removed in version 2.0.0-nullsafety.0 because it was seen complex.
