### ISSUE TITLE
[Question] Is this only ChaCha20 or ChaCha20-Poly1305 ?

### ISSUE THREAD

**Issue by pY4x3g** [dint-dev/cryptography#4]
Hi,

its not clear for me if this is only the encryption ChaCha20 or it has the authentication with poly1305 included as given in https://tools.ietf.org/html/rfc7539.

Thank you for your answer.

Edit: Since the test generates 3 bytes from 3 bytes I assume that poly1305 is not part of this algorithm? Any chance you will implement the ChaCha20-poly1305 ? :)

**Comment by terrier989** [comment]
Correct, this package doesn't contain AEAD_CHACHA20_POLY1305 yet.

**Comment by terrier989** [comment]
The package now contains the AEAD algorithm.
