### ISSUE TITLE
Use an Uint8 or List<int> as SecretKey or Nonce

### ISSUE THREAD

**Issue by jxstxn1** [dint-dev/cryptography#40]
### Whats the problem?
In my current project we need to store the Nonce and the SecretKey of AES-GCM permanently.
We use a Secure Key Vault for this.
The problem it only can handle Strings. So I extracted the Key in an Uint8List, and then casted the List to an Hex String and stored it.
But I can't do it in the other direction.
I'm unable to cast the Uint8List back into the SecretKey or the Nonce.
Pls add an Method for this

**Comment by wenxiangjiang** [comment]
Have you found an alternative method please ? @jxstxn1

**Comment by jxstxn1** [comment]
At this day I was to tired to realise I can use the constructor of the Nonce and Secretkey

`
SecretKey myKey = new SecretKey(uint8ListHere);
Nonce myNonce = new Nonce(uint8ListHere);`

**Comment by wenxiangjiang** [comment]
Thanks, I didn't think of this method at all. @jxstxn1

**Comment by jxstxn1** [comment]
No problem, I also didn't get it in at the beginning but then totally tired I reads the Documentation and found the possibility to use the Constructor :)
