### ISSUE TITLE
AesCbc (null safety) set nonce length?

### ISSUE THREAD

**Issue by flukejones** [dint-dev/cryptography#41]
I'm currently using the null-unsafe version, CBC with a nonce length of 16. This is required due to an external implementation.

We're trying to update the codebase to sound null safety but the blocker is being able to set the nonce length here - I can't seem to see any way of doing so, and there doesn't appear to be a constructor arg to do it either?

**Comment by flukejones** [comment]
Am I reading this right???

[`///   * [nonceLength] is 12 bytes by default.`](https://github.com/dint-dev/cryptography/blob/48b3d7a89fbb9378dc573183cadf01766cc19bf4/cryptography/lib/src/cryptography/algorithms.dart#L21)

But further down is [`  int get nonceLength => 16;`](https://github.com/dint-dev/cryptography/blob/48b3d7a89fbb9378dc573183cadf01766cc19bf4/cryptography/lib/src/cryptography/algorithms.dart#L96)

What is correct here?

Same for AesCtr:
```
abstract class AesCtr extends StreamingCipher {
...
  factory AesCtr.with128bits({
    required MacAlgorithm macAlgorithm,
    int nonceLength = 12,
  }) {
    return AesCtr._(
      macAlgorithm: macAlgorithm,
      secretKeyLength: 16,
    );
  }
  ...
  @override
  int get nonceLength => 16;
```

**Comment by terrier989** [comment]
This is fixed in the current version. The nonce is always 16 bytes and gets incremented correctly.
