### ISSUE TITLE
AES GCM without MAC fails after 2.0 upgrade

### ISSUE THREAD

**Issue by gpeal** [dint-dev/cryptography#45]
I'm upgrading our app from 1.4.1 to 2.0.0-nullsafety.2. Before the update, I didn't need a MAC for aes gcm decrypt. However, after the update, it seems as if one is required.

[The docs](https://pub.dev/documentation/cryptography/2.0.0-nullsafety.2/cryptography/AesGcm-class.html) simply encrypt and decrypt the same data so you can use the secret box you get after the encryption step which will use the [internal mac algorithm](https://github.com/dint-dev/cryptography/blob/b86fb5c099cc80e937a4a348de14a06ad44a5e5b/cryptography/lib/src/dart/aes_gcm.dart#L335).

I can't use the encrypt function to get the secret box because we only get the nonce and cipher text over the wire.

I can't use the SecretBox constructor because it requires a mac, which I don't have.

I can't use SecretBox.fromConcatenation because it requires a mac length, which I don't have and 0 fails [this check](https://github.com/dint-dev/cryptography/blob/b86fb5c099cc80e937a4a348de14a06ad44a5e5b/cryptography/lib/src/dart/aes_gcm.dart#L111).

Is this a bug in 2.0 or am I doing something wrong here?

**Comment by CDDelta** [comment]
In 1.0 and many other implementations of AES-GCM, the MAC is concatenated to the end of the cipher text. This is what I do:

```dart
import 'package:cryptography/cryptography.dart';

final sha256 = Sha256();

/// Returns a [SecretBox] that is compatible with our past use of AES-GCM where the cipher text
/// was appended with the MAC and the nonce was stored separately.
SecretBox secretBoxFromDataWithMacConcatenation(
  Uint8List data, {
  int macByteLength = 16,
  Uint8List nonce,
}) =>
    SecretBox(
      Uint8List.sublistView(data, 0, data.lengthInBytes - macByteLength),
      mac: Mac(Uint8List.sublistView(data, data.lengthInBytes - macByteLength)),
      nonce: nonce,
    );
```

It would be nice if this were integrated into the package though or even the default as it is a rather common pattern.

**Comment by gpeal** [comment]
@CDDelta Aha! This worked! Thank you so much. Adding this to the docs would be extremely helpful! Another typo in the docs is that decrypt calls encrypt instead of decrypt
![image](https://user-images.githubusercontent.com/1307745/107731754-96ca9b80-6cab-11eb-840f-a7553a549378.png)

**Comment by maltemedocs** [comment]
Without this fix, this breaks compatibility with encrypted data created with prior versions of this library. Are there no plans to address this highly severe issue?

**Comment by DanielSoCra** [comment]
Why is this issue closed? The documentation is still not fixed, and the issue still exists.
