### ISSUE TITLE
Migration from 1.4.1 to 2.0.1

### ISSUE THREAD

**Issue by xandros6** [dint-dev/cryptography#48]
Hi,
I have third party code based to 1.4.1 and I want to move it to 2.0.1. 
Can you help in the migration please.
Thanks!

I attach the file to migrate in the 1.4.1 version (is dart renamed to txt to allow upload).
[security1.txt](https://github.com/dint-dev/cryptography/files/6097534/security1.txt)

`

`

**Comment by ttorbik** [comment]
I would also like a guide for this.

**Comment by terrier989** [comment]
I'm afraid this would take too many minutes for pro bono consulting.
