### ISSUE TITLE
SecretBox incorrectly parsed when using fromConcatenation

### ISSUE THREAD

**Issue by zyrwix** [dint-dev/cryptography#55]
SecretBox is created with the incorrect value of cipherText, when it is created from concatenated list. Issue is present in line 153 of secret_box.dart, where the cipherText offset is set to 0, insted of 0 + noonceLenght. Thus created SecretBox has wrong cipherText value and as such is unusable.

**Comment by maxfornacon** [comment]
There is already a pull request that should fix this issue. #51
In the mean time you can try the workaround mentioned in #49

**Comment by terrier989** [comment]
Fixed in 2.0.2.
