### ISSUE TITLE
Padding for AES-CBC-256

### ISSUE THREAD

**Issue by huitingyeong** [dint-dev/cryptography#58]
Hi,
Is there any support for padding for AES CBC 256 cleartext? Like PKCS7?
Or will i have to use an external package?

**Comment by terrier989** [comment]
Hi! Thanks for the issue report. The class `AesCbc` uses the same padding as Web Crypto API, which is PKCS7.

AES-CBC standard allows any padding to be used. If someone wanted to use other padding than PKCS7, we could add an optional named parameter to `AesCbc()` constructor (with a default value `const Pkcs7Padding()`).
