### ISSUE TITLE
How to convert the remote public key to publicKey

### ISSUE THREAD

**Issue by gggitpl** [dint-dev/cryptography#59]
cryptography: ^1.4.1

I didn't find any way

**Comment by maxfornacon** [comment]
I guess you receive the remote key either as `List<int>` or `Uint8List`.
It should be something like this:
```
List<int> remoteKeyBytes = [1, 2, 3];
PublicKey publicKey = PublicKey(remoteKeyBytes);
```

**Comment by gggitpl** [comment]
@maxfornacon thank you very much
