### ISSUE TITLE
doc typo

### ISSUE THREAD

**Issue by nao3301** [dint-dev/cryptography#6]
on [doc]https://pub.dev/documentation/cryptography/latest/cryptography/ecdhP521-constant.html) is the remoteKey not used. 
'
final sharedSecretKey = await algorithm.secretKey(
    localPrivateKey: localKeyPair.privateKey,
    remotePublicKey: localKeyPair.publicKey,
  );
'
should be:
'
 var sharedSecret = await x25519.sharedSecret(
    localPrivateKey: localKeyPair.privateKey,
    remotePublicKey: remoteKeyPair.publicKey,
  );
'

**Comment by terrier989** [comment]
Thanks for the report! Fixed in 0.3.0.
