### ISSUE TITLE
[Question]: How can I implement MLS ratchet tree (TreeKEM)?

### ISSUE THREAD

**Issue by Dekhnar** [dint-dev/cryptography#60]
Hello I'm new in cryptography,

I'm trying to create an E2EE messenger, I want to create an MLS Tree  (TreeKEM) someone can help me?

**Comment by Dekhnar** [comment]
@terrier989 any suggestions

**Comment by maxfornacon** [comment]
I guess this is the wrong platform for your question. I would suggest searching for help on stackoverflow.

**Comment by Dekhnar** [comment]
indeed ty for you answer
