### ISSUE TITLE
After Adding the cryptography Pubs 

### ISSUE THREAD

**Issue by LokiRathod** [dint-dev/cryptography#61]
After adding cryptography: ^2.0.1

**Getting the below error:** 

Because built_value >=8.0.0-nullsafety.0 <8.0.0 depends on built_collection ^5.0.0-nullsafety and built_value >=5.5.5 <8.0.0-nullsafety.0 depends on fixnum ^0.10.0, built_value >=5.5.5 <=8.0.0-nullsafety.0 requires built_collection ^5.0.0-nullsafety or fixnum ^0.10.0.
(1) So, because built_value >=8.0.0 depends on built_collection ^5.0.0, built_value >=5.5.5 requires built_collection ^5.0.0-nullsafety or fixnum ^0.10.0.

    Because code_builder >=3.1.3 <3.2.1 depends on built_value ^6.0.0 and code_builder >=3.2.1 <3.6.0 depends on built_value ^7.0.0, code_builder >=3.1.3 <3.6.0 requires built_value ^6.0.0 or ^7.0.0.
    And because code_builder ^3.6.0 depends on built_value >=7.0.0 <9.0.0, code_builder ^3.1.3 requires built_value ^6.0.0 or >=7.0.0 <9.0.0.
    And because built_value >=5.5.5 requires built_collection ^5.0.0-nullsafety or fixnum ^0.10.0 (1), code_builder ^3.1.3 requires built_collection ^5.0.0-nullsafety or fixnum ^0.10.0.
    And because retrofit_generator 1.4.1+3 depends on both built_collection ^4.2.0 and code_builder ^3.2.0, retrofit_generator 1.4.1+3 requires fixnum ^0.10.0.
    And because no versions of retrofit_generator match >1.4.1+3 <2.0.0 and cryptography >=2.0.0 depends on fixnum ^1.0.0, retrofit_generator ^1.4.1+3 is incompatible with cryptography >=2.0.0.
    So, because consumer_moola depends on both cryptography ^2.0.1 and retrofit_generator ^1.4.1+3, version solving failed.
pub get failed (1;     So, because consumer_moola depends on both cryptography ^2.0.1 and retrofit_generator ^1.4.1+3, version solving failed.)

**dependencies:**
  flutter:
    sdk: flutter
  retrofit: ^1.3.4+1
  logger: ^0.8.3
  json_annotation: ^3.0.1
  provider: ^4.0.1
  intro_slider: ^2.3.1
  local_auth: ^0.6.3+4
  qr_code_scanner: ^0.3.5
  qr_flutter: ^3.1.0
  jwt_decoder: ^2.0.1
  cryptography: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

**dev_dependencies:**
  flutter_test:
    sdk: flutter
  connectivity: ^0.4.5+2
  http: ^0.12.0+4
  toast: ^0.1.5
  shared_preferences: ^0.5.6+3
  flutter_svg: ^0.15.0
  dio: ^3.0.1
  build_runner: ^1.8.1
  retrofit_generator: ^1.4.1+3
  json_serializable: ^3.3.0
  intl: ^0.16.1
  pin_code_fields: ^4.0.0
  gradient_text: ^1.0.2

Please let me know what i can do here .?

**Comment by terrier989** [comment]
Hi! The issue is caused by old dependency constraints in `package:retrofit_generator`. You can use `dependency_overrides` as a workaround.
