### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by steebchen** [dint-dev/cryptography#64]
It would be great if this module could support the new [Dart null safety](https://dart.dev/null-safety) and publish it on pub.dev.

**Comment by maxfornacon** [comment]
It supports null safety and is already published to pub.dev: [https://pub.dev/packages/cryptography](url)

**Comment by steebchen** [comment]
I just realised this is a monorepo... I opened this issue because I didn't see a "null safety" tag at https://pub.dev/packages/kms.

**Comment by terrier989** [comment]
The package already supports null-safety.
