### ISSUE TITLE
Could be a mistake on implementation?

### ISSUE THREAD

**Issue by hndrbrm** [dint-dev/cryptography#70]
The implementation of [SubWord](https://en.wikipedia.org/wiki/Rijndael_S-box) in [aes_impl.dart](https://github.com/dint-dev/cryptography/blob/master/cryptography/lib/src/dart/aes_impl.dart):

<details>

```dart
/// Used for expanding decryption key.
int _subW(int w) {
  final s = constants.s;
  return (0xFFFFFFFF & (s[0xFF & (w >> 24)]) << 24) |
      (0xFFFFFFFF & (s[0xFF & (w >> 16)]) << 16) |
      (0xFFFFFFFF & (s[0xFF & (w >> 8)]) << 8) |
      (0xFFFFFFFF & (s[0xFF & w]));
}
```

</details>

I confuse why it using or (|) not xor (^).
Is it already correct or is it a typo?

**Comment by terrier989** [comment]
Constant `s` is a list of bytes. Each of the four bytes from `s` occupies non-overlapping bits in the 32-bit output, which means that either `^` or `|` is OK. The 0xFFFFFFFF is a possibly useless optimization hint to the compiler that the output takes only 32 bits.
