### ISSUE TITLE
Investigate changing `dart:io` import to `dart:typed_data` in `mac_algorithm.dart` so it works for web applications

### ISSUE THREAD

**Issue by grantnelson-wf** [dint-dev/cryptography#72]
I have a [simple project](https://github.com/grantnelson-wf/dartCompTest/tree/main/treatments/libdeps1) (an example blockchain as part of a larger experiment) which uses this package. The blockchain has a web frontend to interact with it. In order to build the project for the web I needed to change the import on [line 16 of mac_algorithm.dart](https://github.com/dint-dev/cryptography/blob/master/cryptography/lib/src/cryptography/mac_algorithm.dart#L16) from `import 'dart:io';` to `import 'dart:typed_data';`. The import is for `BytesBuilder`. The `io` one wasn't working for `webdev` but `typed_data` did. With this change I was able to build and run my example code, but I haven't run your tests or tried to run it on command line with the changes. It still needs to be investigated and vetted, hence I created this issue instead of a just putting up my fork's PR.

**Comment by terrier989** [comment]
Thanks! Fixed in 2.0.4.
