### ISSUE TITLE
Xchacha20 issue going from 2.0.4 to 2.0.5

### ISSUE THREAD

**Issue by STINightFall** [dint-dev/cryptography#85]
A string encrypted with Xchacha20 on version 2.4 can't be decrypted with 2.5.  Rolling back to 2.4, it works as expected.  The error is "SecretBox has wrong message authentication code (MAC)"

Is 2.5 not backwards compatible with 2.4?

Here is the cipher:

 final cipher = Xchacha20(macAlgorithm: Hmac.sha256());

Thanks!

**Comment by terrier989** [comment]
I believe this was fixed in 2.2.0. The problem was that Chacha20 and Chacha20-Poly1305-AEAD do not produce the same cipher text (because of the first block) and Xchacha20 had a bug when something like HMAC_SHA256 was used instead of Xchacha20.poly1305.
