### ISSUE TITLE
call value of non-function type 'FlutterBinaryMessenger' 

### ISSUE THREAD

**Issue by writethesky** [dint-dev/cryptography#87]
using 
cryptography: ^2.0.5
cryptography_flutter: ^2.0.2

failed to build 

![image](https://user-images.githubusercontent.com/7201443/146780310-fb6e1833-b2f2-48c2-b6e6-3eed65e41d22.png)

**Comment by terrier989** [comment]
Fixed in cryptography_flutter 2.1.0.
