### ISSUE TITLE
Seed RSA key generator?

### ISSUE THREAD

**Issue by tjcampanella** [dint-dev/cryptography#90]
Is there anyway to seed the RSA key generator? I am looking to seed it to produce the same key pair based on a hashed password. Is there anyway to do that with this package? The reason is I need a way for users to be able to generate the same key pair on multiple devices without having to share it explicitly. My idea being when they sign in on a new device I can generate their key-pair based on their hashed password. Let me know if this package supports this or if there is a better way I should do this. Thanks.

**Comment by terrier989** [comment]
We don't have any RSA related implementation in pure Dart so this would need support from the platform APIs we use.
