### ISSUE TITLE
AES 256 GCM media file encryption performance issue

### ISSUE THREAD

**Issue by coderGirl9796** [dint-dev/cryptography#97]
Hello, there

I am using AES 256 GCM algorithm to encrypt normal text message and media files. The issue is when I try to encrypt media file which has size 1 MB, it takes 1 to 1.5 min to encrypt it.

Would you help me out with this?

**Comment by RobotKSR** [comment]
Same issue here. Maybe it is because of poor documentation, so we don't know how to encrypt and decrypt file efficiently.

**Comment by coderGirl9796** [comment]
> Same issue here. Maybe it is because of poor documentation, so we don't know how to encrypt and decrypt file efficiently. Please share your code if you solved this problem.

Hey, I have changed the algorithm for media file encryption. I have used AES CBC for it and it is efficient for media file encryption.

**Comment by RobotKSR** [comment]
@coderGirl9796, thanks a lot! Changing to AES CBC worked great, significantly better. It's just left to wonder why some people tell that AES GCM is more efficient in some of issues.

**Comment by terrier989** [comment]
This was fixed in cryptography_flutter 2.1.0.
